[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[functions]
  # Netlify requires serverless functions to be in the functions directory
  # and use the .js extension with proper handler exports
